"use client";

import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { supabase } from "../../lib/supabase";

/**
 * Email confirmation callback page.
 *
 * Supabase sends users here after they click the confirmation link in their
 * inbox. The URL contains a `code` parameter generated by the PKCE flow that
 * was initiated in the browser during signUp().  Because the PKCE code
 * verifier was stored in localStorage (by the browser Supabase client) at
 * sign-up time, this exchange MUST happen client-side — a server Route Handler
 * would have no access to localStorage and cannot complete the exchange.
 *
 * On success  → redirect to `next` (defaults to "/")
 * On failure  → redirect to "/auth?error=confirmation_failed"
 */
export default function AuthCallbackPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [status, setStatus] = useState<"loading" | "error">("loading");

  useEffect(() => {
    const code = searchParams.get("code");
    const next = searchParams.get("next") ?? "/";

    if (!code) {
      router.replace("/auth?error=confirmation_failed");
      return;
    }

    supabase.auth
      .exchangeCodeForSession(code)
      .then(({ error }) => {
        if (error) {
          console.error("[auth/callback] exchangeCodeForSession failed:", error.message);
          setStatus("error");
          router.replace("/auth?error=confirmation_failed");
        } else {
          document.cookie = "wwe_auth=1; path=/; max-age=31536000; SameSite=Lax";
          router.replace(next);
        }
      });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  if (status === "error") return null;

  return (
    <main
      className="min-h-screen flex items-center justify-center"
      style={{ background: "#0B0805" }}
    >
      <p
        style={{
          fontFamily: "var(--font-quicksand)",
          fontWeight: 600,
          fontSize: 16,
          color: "#897E73",
        }}
      >
        Confirming your account…
      </p>
    </main>
  );
}
