"use client";

import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { supabase } from "../../lib/supabase";

/**
 * Email confirmation callback page.
 *
 * Supabase sends users here after they click the confirmation link in their
 * inbox. The URL contains a `code` parameter generated by the PKCE flow that
 * was initiated in the browser during signUp().  Because the PKCE code
 * verifier was stored in localStorage (by the browser Supabase client) at
 * sign-up time, this exchange MUST happen client-side — a server Route Handler
 * would have no access to localStorage and cannot complete the exchange.
 *
 * On success  → redirect to `next` (defaults to "/")
 * On failure  → redirect to "/auth?error=confirmation_failed"
 */
export default function AuthCallbackPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [status, setStatus] = useState<"loading" | "error">("loading");

  useEffect(() => {
    const code = searchParams.get("code");
    const next = searchParams.get("next") ?? "/";
    const typeParam = searchParams.get("type");

    if (!code) {
      router.replace("/auth?error=confirmation_failed");
      return;
    }

    // Subscribe before exchanging so PASSWORD_RECOVERY fires before .then() resolves.
    // Supabase fires onAuthStateChange synchronously during session storage, so
    // isRecovery is guaranteed to be set before the .then() callback runs.
    let isRecovery = false;
    const { data: { subscription } } = supabase.auth.onAuthStateChange((event) => {
      if (event === "PASSWORD_RECOVERY") {
        isRecovery = true;
      }
    });

    supabase.auth
      .exchangeCodeForSession(code)
      .then(async ({ error }) => {
        subscription.unsubscribe();
        if (error) {
          console.error("[auth/callback] exchangeCodeForSession failed:", error.message);
          setStatus("error");
          router.replace("/auth?error=confirmation_failed");
        } else {
          document.cookie = "wwe_auth=1; path=/; max-age=31536000; SameSite=Lax";

          if (typeParam === "recovery" || isRecovery) {
            router.replace("/auth/reset");
            return;
          }

          // Detect Founding Taster OAuth return.
          // Primary signal: ?founding_taster=1 injected into the OAuth redirectTo URL.
          // Fallback: localStorage flag survives the same-origin OAuth round-trip.
          const foundingParam = searchParams.get("founding_taster") === "1";
          const foundingLocal =
            typeof window !== "undefined" &&
            localStorage.getItem("founding_taster_access") === "true";
          const foundingSession =
            typeof window !== "undefined" &&
            sessionStorage.getItem("founding_taster_intent") === "true";
          const isFoundingTaster = foundingParam || foundingLocal || foundingSession;

          if (isFoundingTaster) {
            // Try to stamp is_founding_taster = true on the profile now if it is
            // already linked to this auth user (returning users / same-device signups).
            // For brand-new OAuth users whose profile has not been linked yet,
            // we leave founding_taster_access in localStorage so ProfileProvider's
            // applyFoundingTasterFlag() can consume it during its init cycle.
            let appliedViaCallback = false;
            try {
              const { data: { user } } = await supabase.auth.getUser();
              if (user?.id) {
                const { data: profileRow } = await supabase
                  .from("profiles")
                  .select("user_id")
                  .eq("auth_user_id", user.id)
                  .maybeSingle();
                if (profileRow?.user_id) {
                  await supabase
                    .from("profiles")
                    .update({ is_founding_taster: true, updated_at: new Date().toISOString() })
                    .eq("user_id", profileRow.user_id);
                  if (typeof window !== "undefined") {
                    localStorage.removeItem("founding_taster_access");
                  }
                  appliedViaCallback = true;
                }
              }
            } catch (err) {
              console.error("[auth/callback] founding taster apply error:", err);
            }
            if (!appliedViaCallback) {
              // Profile not linked yet — founding_taster_access preserved for ProfileProvider.
              console.log("[auth/callback] profile not yet linked; founding flag preserved for ProfileProvider");
            }
            router.replace("/founding-welcome?founding_taster=1");
          } else {
            // No founding intent — clear any stale flag and continue normally.
            if (typeof window !== "undefined") {
              localStorage.removeItem("founding_taster_access");
            }
            router.replace(next);
          }
        }
      });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  if (status === "error") return null;

  return (
    <main
      className="min-h-screen flex items-center justify-center"
      style={{ background: "#0B0805" }}
    >
      <p
        style={{
          fontFamily: "var(--font-quicksand)",
          fontWeight: 600,
          fontSize: 16,
          color: "#897E73",
        }}
      >
        Confirming your account…
      </p>
    </main>
  );
}
